import i18n from "i18n";
import { RegisterFormState, StateData } from "utils/types";

export const getInitialFormState = (
  initform: RegisterFormState | undefined,
  partner: string | undefined,
  state: StateData,
  zip: string,
  email: string,
): RegisterFormState => ({
  partner_id: Number(partner) || 1,
  lang: i18n.language,

  name_title: initform?.name_title || "",
  first_name: initform?.first_name || "",
  middle_name: initform?.middle_name || "",
  last_name: initform?.last_name || "",
  suffix: initform?.suffix || "",
  will_be_18_by_election: initform?.will_be_18_by_election || false,
  us_citizen: initform?.us_citizen || false,
  email_address: initform?.email_address || email,

  change_of_name: initform?.change_of_name || false,
  prev_name_title: initform?.prev_name_title || "",
  prev_first_name: initform?.prev_first_name || "",
  prev_middle_name: initform?.prev_middle_name || "",
  prev_last_name: initform?.prev_last_name || "",
  prev_name_suffix: initform?.prev_name_suffix || "",

  home_address: initform?.home_address || "",
  address_line_2: initform?.address_line_2 || "",
  home_unit_type: initform?.home_unit_type || "",
  home_unit: initform?.home_unit || "",
  home_city: initform?.home_city || "",
  state: initform?.state || state.abbreviation,
  home_zip_code: initform?.home_zip_code || zip,

  mailing_unit_type: initform?.mailing_unit_type || "",
  mailing_unit_number: initform?.mailing_unit_number || "",
  mailing_address: initform?.mailing_address || "",
  mailing_unit: initform?.mailing_unit || "",
  mailing_city: initform?.mailing_city || "",
  mailing_state: initform?.mailing_state || "",
  mailing_zip_code: initform?.mailing_zip_code || "",

  change_of_address: initform?.change_of_address || false,
  prev_address: initform?.prev_address || "",
  prev_unit: initform?.prev_unit || "",
  prev_city: initform?.prev_city || "",
  prev_state: initform?.prev_state || "",
  prev_zip_code: initform?.prev_zip_code || "",
  prev_unit_number: initform?.prev_unit_number || "",
  prev_unit_type: initform?.prev_unit_type || "",

  race: initform?.race || "",
  party: initform?.party || "",
  changed_party: initform?.changed_party || false,
  home_county: initform?.home_county || "",
  signature_base64: initform?.signature_base64 || "",
  signature_upload_method: initform?.signature_upload_method || "",

  birthMonth: initform?.birthMonth || "",
  birthDay: initform?.birthDay || "",
  birthYear: initform?.birthYear || "",
  date_of_birth: initform?.date_of_birth || "",
  dob_routing_outcome: initform?.dob_routing_outcome ?? "",
  phone: initform?.phone || "",

  issueMonth: initform?.issueMonth || "",
  issueDay: initform?.issueDay || "",
  issueYear: initform?.issueYear || "",
  date_of_issue: initform?.date_of_issue || "",
  military_service: initform?.military_service || false,
  non_standard_address: initform?.non_standard_address || "",

  opt_in_sms: initform?.opt_in_sms || false,
  opt_in_email: initform?.opt_in_email || true,
  volunteer: initform?.volunteer || false,
  mailForm: initform?.mailForm || false,
  survey_question_1: initform?.survey_question_1 || "",
  survey_answer_1: initform?.survey_answer_1 || "",
  survey_question_2: initform?.survey_question_2 || "",
  survey_answer_2: initform?.survey_answer_2 || "",

  residency_duration_ack: initform?.residency_duration_ack || false,
  cancel_previous_registration_ack:
    initform?.cancel_previous_registration_ack || false,
  use_stored_signature_ack: initform?.use_stored_signature_ack || false,
  updated_dln_recently: initform?.updated_dln_recently || "no",
  request_duplicate_dln_today: initform?.request_duplicate_dln_today || "no",
  age_eligibility: initform?.age_eligibility || false,

  full_name: initform?.full_name || "",
  state_id_number: initform?.state_id_number || "",
  eye_color: initform?.eye_color || "",
  last_four_ss_number: initform?.last_four_ss_number || "",
  has_no_state_license: initform?.has_no_state_license ?? null,
  has_no_ssn: initform?.has_no_ssn ?? null,
  helper_electronic_signature_acknowledged:
    initform?.helper_electronic_signature_acknowledged || false,

  upload: initform?.upload || "",
  someone_helped: initform?.someone_helped || false,
  helper_name: initform?.helper_name || "",
  helper_address: initform?.helper_address || "",
  helper_phone: initform?.helper_phone || "",

  street_name: initform?.street_name || "",
  street_number: initform?.street_number || "",
  street_type: initform?.street_type || "",
  street_direction: initform?.street_direction || "",

  has_mailing_address: initform?.has_mailing_address || false,
  mailing_postal_code: initform?.mailing_postal_code || "",
  mailing_address_number: initform?.mailing_postal_code || "",
  mailing_address_street_name: initform?.mailing_postal_code || "",
  mailing_address_street_type: initform?.mailing_postal_code || "",
  mailing_address_type: initform?.mailing_address_type || "STANDARD",
  mailing_po_box_number: initform?.mailing_po_box_number || "",
  mailing_box_group_type: initform?.mailing_box_group_type || "",
  mailing_box_group_number: initform?.mailing_box_group_number || "",
  mailing_box_number: initform?.mailing_box_number || "",
  mailing_apo: initform?.mailing_apo || "",
  mailing_ap: initform?.mailing_ap || "",
  mailing_address_line1: initform?.mailing_address_line1 || "",
  mailing_address_line2: initform?.mailing_address_line2 || "",
  mailing_address_line3: initform?.mailing_address_line3 || "",
  mailing_country: initform?.mailing_country || "",
});
